# Generated by Django 4.1.5 on 2023-05-24 05:18

import django.core.validators
from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('asset_id', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('price_date', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('close_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('high_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('adjusted_close_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('asset_id', models.CharField(max_length=50)),
                ('open_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('close_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('adjusted_close_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
